
# tap repositories and their packages

tap homebrew/core
brew adns
brew aria2
brew autoconf
brew bandwhich
brew bat
brew bdw-gc
brew cairo
brew cmake
brew convmv
brew direnv
brew docker
brew docker-compose
brew docker-machine
brew dust
brew emacs
brew exa
brew fd
brew fdk-aac
brew ffmpeg --with-fdk-aac
brew fish
brew fontconfig
brew freetype
brew gcc
brew gdbm
brew gettext
brew ghq
brew gibo
brew giflib
brew git
brew glib
brew gmp
brew gnutls
brew go
brew gradle
brew grex
brew guile
brew httpie
brew hyperfine
brew icu4c
brew id3lib
brew id3v2
brew ilmbase
brew imagemagick
brew isl
brew jpeg
brew jq
brew lame
brew libassuan
brew libde265
brew libev
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew libksba
brew libmpc
brew libomp
brew libpng
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libwebsockets
brew libyaml
brew little-cms2
brew mas
brew mkcert
brew mpfr
brew nasm
brew nettle
brew nkf
brew node-build
brew nodenv
brew npth
brew nspr
brew nss
brew oniguruma
brew openexr
brew openjpeg
brew openssl@1.1
brew p11-kit
brew pcre
brew pcre2
brew peco
brew pinentry
brew pixman
brew pkg-config
brew postgresql
brew procs
brew protobuf
brew rbenv
brew readline
brew ripgrep
brew ruby-build
brew sbt
brew sd
brew shared-mime-info
brew sqlite
brew texi2html
brew tokei
brew unbound
brew valgrind
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew zsh

tap homebrew/cask-fonts
cask font-myrica

tap homebrew/cask-versions
cask google-chrome-canary

tap homebrew/services

tap homebrew/cask
cask 1password
cask coteditor
cask cyberduck
cask docker
cask dropbox
cask firefox
cask google-chrome
cask intellij-idea-ce
cask night-owl
cask skype
cask sublime-text
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask xld

tap itchyny/fillin

tap rcmdnk/file
brew brew-file

tap shogogg/cask-atok
cask atok-passport

# Other Homebrew packages
brew fillin
brew gpg2
brew openssl
brew python
brew python@2

# Other Cask applications
cask java

# App Store applications
appstore 405843582 Alfred (1.2)
appstore 1024640650 CotEditor (3.5.0)
appstore 409183694 Keynote (8.1)
appstore 411213048 LadioCast (000012004)
appstore 539883307 LINE (5.9.2)
appstore 634148309 Logic Pro X (10.4.1)
appstore 409201541 Pages (7.1)
appstore 407963104 Pixelmator (3.7.3)
appstore 425424351 The Unarchiver (4.0.0)
