name: Auto-fix Dependencies

on:
  workflow_run:
    workflows:
      # Update to match your CI workflow name(s)
      - "CI Status Check"
    types:
      - completed

jobs:
  auto-fix:
    # Only run when CI fails on dependency bot PRs
    if: |
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.event == 'pull_request'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Get PR information
        id: pr-info
        uses: actions/github-script@v7
        with:
          script: |
            // Get PR from the workflow_run event
            const prs = context.payload.workflow_run.pull_requests;
            if (!prs || prs.length === 0) {
              core.setFailed('No PR found in workflow_run event');
              return;
            }

            const pr = prs[0];

            // Get full PR details
            const { data: prData } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });

            // Check if PR is from a dependency bot
            const author = prData.user.login;
            const isBot = author === 'renovate[bot]' || author === 'dependabot[bot]';

            if (!isBot) {
              core.info(`Skipping: PR author is ${author}, not a dependency bot`);
              core.setOutput('skip', 'true');
              return;
            }

            core.setOutput('skip', 'false');
            core.setOutput('pr_number', pr.number);
            core.setOutput('head_ref', prData.head.ref);
            core.setOutput('pr_url', prData.html_url);
            core.setOutput('pr_title', prData.title);
            core.setOutput('pr_author', author);

      - name: Checkout repository
        if: steps.pr-info.outputs.skip != 'true'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ steps.pr-info.outputs.head_ref }}
          persist-credentials: false

      - name: Auto-fix dependencies
        if: steps.pr-info.outputs.skip != 'true'
        id: auto-fix
        uses: anthropics/claude-code-action@v1.0.29
        with:
          # Authentication: Choose ONE of the following methods

          # Option A (Recommended): Claude Code OAuth token
          # Setup: /install-github-app in Claude Code CLI
          # Or manually: https://claude.ai/settings/oauth
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Option B: Anthropic API key
          # Create at: https://console.anthropic.com/settings/keys
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          use_bedrock: false
          use_vertex: false
          prompt: |
            **CI Failed - Fix Required**

            A dependency update PR from ${{ steps.pr-info.outputs.pr_author }} has failed the status check.

            PR: ${{ steps.pr-info.outputs.pr_url }}
            Title: ${{ steps.pr-info.outputs.pr_title }}

            **Your task:**
            1. Check which CI workflows failed: `gh pr checks ${{ steps.pr-info.outputs.pr_number }}`
            2. Investigate failures using `gh run view` and checking test logs
            3. Fix the issues (e.g., update lockfile, resolve conflicts, fix breaking changes)
            4. Commit and push the fixes
            5. DO NOT merge - auto-merge will handle it once all CI checks pass

            **Important:**
            - Focus only on fixing the CI failures
            - After pushing fixes, verify all checks pass with `gh pr checks`
            - Do not manually merge - this repository uses auto-merge for dependency PRs
            - If the issue cannot be fixed automatically, leave a detailed comment explaining the problem

          # Adjust allowed tools based on your project needs
          claude_args: '--allowed-tools "Bash(gh:*),Bash(git:*),Bash(pnpm:*),Bash(npm:*),Read,Write,Edit,Glob,Grep"'
