name: Renovate

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    # For team setups, consider using an environment to scope secrets and branches.
    # environment: renovate
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Run Renovate
        uses: renovatebot/github-action@v44
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: .github/renovate.json5
          repositories: ${{ github.repository }}
