model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.readability]
command = "npx"
args = ["-y", "@mizchi/readability@latest", "--mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]
