name: Install chezmoi
description: Install chezmoi binary

inputs:
  install-dir:
    description: 'Installation directory'
    required: false
    default: '/usr/local/bin'
  add-to-path:
    description: 'Add installation directory to PATH'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install chezmoi
      shell: bash
      env:
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: |
        sh -c "$(curl -fsLS https://get.chezmoi.io)" -- -b "${INSTALL_DIR}"

    - name: Add to PATH
      if: inputs.add-to-path == 'true'
      shell: bash
      env:
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: echo "${INSTALL_DIR}" >> "$GITHUB_PATH"
