#!/bin/bash
# Shows missing plugins and generates install commands
# Usage: ~/.claude/scripts/show-missing-plugins.sh
#
# Compares .settings.plugins.json with installed_plugins.json
# and outputs install commands for missing plugins.

set -euo pipefail

CHEZMOI_SOURCE_DIR="${CHEZMOI_SOURCE_DIR:-$(chezmoi source-path 2>/dev/null || echo "$HOME/.local/share/chezmoi")}"
PLUGINS_FILE="${CHEZMOI_SOURCE_DIR}/dot_claude/.settings.plugins.json"
INSTALLED_FILE="$HOME/.claude/plugins/installed_plugins.json"
KNOWN_MARKETPLACES_FILE="$HOME/.claude/plugins/known_marketplaces.json"

# Check if plugins file exists
if [[ ! -f "$PLUGINS_FILE" ]]; then
    echo "❌ .settings.plugins.json not found at $PLUGINS_FILE"
    exit 1
fi

# Get required plugin keys from .settings.plugins.json
# Format: "plugin-name@marketplace"
REQUIRED_PLUGINS=$(jq -r 'keys[]' "$PLUGINS_FILE")

# Get installed plugin keys from installed_plugins.json
if [[ -f "$INSTALLED_FILE" ]]; then
    INSTALLED_PLUGINS=$(jq -r '.plugins // {} | keys[]' "$INSTALLED_FILE")
else
    INSTALLED_PLUGINS=""
fi

# Find missing plugins
MISSING=()
while IFS= read -r plugin; do
    [[ -z "$plugin" ]] && continue
    if ! echo "$INSTALLED_PLUGINS" | grep -qxF "$plugin"; then
        MISSING+=("$plugin")
    fi
done <<< "$REQUIRED_PLUGINS"

# Output results
if [[ ${#MISSING[@]} -eq 0 ]]; then
    echo "✅ All required plugins are installed!"
    exit 0
fi

# Get registered marketplaces from known_marketplaces.json
REGISTERED_MARKETPLACES=""
if [[ -f "$KNOWN_MARKETPLACES_FILE" ]]; then
    REGISTERED_MARKETPLACES=$(jq -r 'keys[]' "$KNOWN_MARKETPLACES_FILE" 2>/dev/null || echo "")
fi

# Collect unique marketplaces needed for missing plugins (using regular array)
MARKETPLACES=()
for plugin in "${MISSING[@]}"; do
    marketplace="${plugin##*@}"
    # Only add if not already registered and not already in list
    if ! echo "$REGISTERED_MARKETPLACES" | grep -qxF "$marketplace"; then
        # Check if already in MARKETPLACES array
        already_added=false
        for m in "${MARKETPLACES[@]+"${MARKETPLACES[@]}"}"; do
            if [[ "$m" == "$marketplace" ]]; then
                already_added=true
                break
            fi
        done
        if [[ "$already_added" == "false" ]]; then
            MARKETPLACES+=("$marketplace")
        fi
    fi
done

echo "📦 Missing plugins (${#MISSING[@]}):"
for plugin in "${MISSING[@]}"; do
    name="${plugin%@*}"
    marketplace="${plugin##*@}"
    echo "   - $name ($marketplace)"
done
echo ""

# Generate installer script
INSTALLER_SCRIPT="$HOME/.claude/scripts/install-missing-plugins.sh"
TOTAL=${#MISSING[@]}

# Helper function to get repo name from marketplace
get_repo_name() {
    local marketplace="$1"
    if [[ "$marketplace" == "claude-code-plugins" ]]; then
        echo "anthropics/claude-code"
    else
        echo "$marketplace"
    fi
}

cat > "$INSTALLER_SCRIPT" << 'HEADER'
#!/bin/bash
# Auto-generated script to install missing plugins
# Generated by show-missing-plugins.sh

set -euo pipefail

# Find claude command
CLAUDE_CMD=""
if command -v claude &>/dev/null; then
    CLAUDE_CMD="claude"
elif [[ -x "$HOME/.claude/local/claude" ]]; then
    CLAUDE_CMD="$HOME/.claude/local/claude"
elif [[ -x "/usr/local/bin/claude" ]]; then
    CLAUDE_CMD="/usr/local/bin/claude"
else
    echo "❌ claude command not found"
    echo "Please ensure Claude Code is installed and in your PATH"
    exit 1
fi

HEADER

# Only add MARKETPLACES array if there are unregistered marketplaces
HAS_UNREGISTERED_MARKETPLACES=false
if [[ ${#MARKETPLACES[@]} -gt 0 ]]; then
    HAS_UNREGISTERED_MARKETPLACES=true
fi

if [[ "$HAS_UNREGISTERED_MARKETPLACES" == "true" ]]; then
    echo "MARKETPLACES=(" >> "$INSTALLER_SCRIPT"
    for marketplace in "${MARKETPLACES[@]}"; do
        echo "    '$(get_repo_name "$marketplace")'" >> "$INSTALLER_SCRIPT"
    done
    echo ")" >> "$INSTALLER_SCRIPT"
else
    echo "MARKETPLACES=()" >> "$INSTALLER_SCRIPT"
fi

cat >> "$INSTALLER_SCRIPT" << 'MIDDLE'

PLUGINS=(
MIDDLE

for plugin in "${MISSING[@]}"; do
    name="${plugin%@*}"
    marketplace="${plugin##*@}"
    if [[ "$marketplace" == "claude-code-plugins" ]]; then
        echo "    '${name}@anthropics/claude-code'" >> "$INSTALLER_SCRIPT"
    else
        echo "    '$plugin'" >> "$INSTALLER_SCRIPT"
    fi
done

cat >> "$INSTALLER_SCRIPT" << 'FOOTER'
)

# Register marketplaces if needed
if [[ ${#MARKETPLACES[@]} -gt 0 ]]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📦 Registering marketplaces..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    for mp in "${MARKETPLACES[@]}"; do
        echo "Registering $mp..."
        if "$CLAUDE_CMD" -p "/plugin marketplace add $mp"; then
            echo "    ✅ Done"
        else
            echo "    ⚠️  May already be registered"
        fi
    done
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Installing ${#PLUGINS[@]} plugins..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

TOTAL=${#PLUGINS[@]}
FAILED=0
i=1
for p in "${PLUGINS[@]}"; do
    echo "[$i/$TOTAL] Installing $p..."
    if "$CLAUDE_CMD" -p "/plugin install $p"; then
        echo "    ✅ Success"
    else
        echo "    ❌ Failed"
        ((FAILED++))
    fi
    ((i++))
    echo ""
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [[ $FAILED -eq 0 ]]; then
    echo "✅ All plugins installed successfully! Restart Claude Code to load them."
else
    echo "⚠️  Done with $FAILED failure(s). Restart Claude Code to load installed plugins."
fi
echo ""

exit $FAILED
FOOTER

chmod +x "$INSTALLER_SCRIPT"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run the installer script:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "    ~/.claude/scripts/install-missing-plugins.sh"
echo ""
