
# tap repositories and their packages

tap homebrew/core
brew aria2
brew autoconf
brew bat
brew cmake
brew docker
brew docker-compose
brew docker-machine
brew emacs
brew exa
brew fd
brew fdk-aac
brew ffmpeg
brew fzf
brew gcc
brew gh
brew ghq
brew git
brew htop
brew icu4c
brew imagemagick
brew jq
brew mkcert
brew nkf
brew peco
brew pkg-config
brew protobuf
brew readline
brew ripgrep
brew ruby-build
brew sqlite
brew tokei
brew webp
brew wget
brew xz
brew zsh

tap homebrew/cask
cask 1password
cask coteditor
cask docker
cask dropbox
cask firefox
cask google-chrome
cask google-chrome@canary
cask raycast
cask virtualbox
cask visual-studio-code
cask vlc
cask xld

# Other Homebrew packages
brew gpg2
brew openssl
brew postgresql
brew python
